---
language: node_js

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=1.10.0
  - EMBER_TRY_SCENARIO=1.11.3
  - EMBER_TRY_SCENARIO=1.12.1
  - EMBER_TRY_SCENARIO=1.13.2

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
